/**
 * Source for the bundled coworking MCP server script.
 *
 * The agent's MCP client spawns this script as a stdio subprocess (per the user-level
 * MCP config we install via `coworking-installer`). The subprocess speaks the MCP wire
 * protocol on stdin/stdout, and connects back to Maestro main via the Unix-domain
 * socket / named pipe whose path is in `MAESTRO_COWORKING_SOCKET`.
 *
 * We write the script as a self-contained CommonJS file to `<userData>/coworking-mcp-server.js`
 * on every app `ready`. That gives us:
 *   - a stable absolute path users can reference in their MCP config (survives upgrades)
 *   - no dependency on the Maestro app bundle being on disk at a known path
 *   - no bundler step in PR #1 (script is plain Node - only built-ins)
 *
 * The script implements just enough of the MCP stdio protocol to advertise the
 * coworking tool suite: terminal reads (`list_terminals`, `read_terminal`), browser
 * reads (`list_browsers`, `get_browser_url`, `read_browser`) and the permission-gated
 * browser interaction tools (`browser_navigate` ... `browser_close_tab`). Anything
 * richer (subscriptions, resource templates, prompts) is a later PR.
 */

const COWORKING_SCRIPT_SOURCE = String.raw`#!/usr/bin/env node
"use strict";
/**
 * Maestro Coworking - MCP stdio server.
 * AUTOGENERATED by Maestro. Do not edit; this file is overwritten on every Maestro launch.
 *
 * Speaks MCP JSON-RPC on stdin/stdout. Translates 'tools/list' and 'tools/call' into
 * IPC requests against the parent Maestro app via a Unix socket / named pipe.
 *
 * Spec: https://modelcontextprotocol.io/specification (subset).
 */
const net = require('net');

// Prefer the per-spawn override (MAESTRO_COWORKING_SOCKET_OVERRIDE), injected by
// ProcessManager into the owning window's agent process so this subprocess binds
// to the bridge of the window that spawned it. Fall back to the shared user-level
// MCP config socket (a single global value, last install wins) for agent CLIs
// that do not propagate env to their MCP subprocess (e.g. Codex).
const SOCKET_PATH =
  process.env.MAESTRO_COWORKING_SOCKET_OVERRIDE || process.env.MAESTRO_COWORKING_SOCKET;
if (!SOCKET_PATH) {
  process.stderr.write('[maestro-coworking] MAESTRO_COWORKING_SOCKET env var is required\n');
  process.exit(1);
}

// SESSION_ID identifies which Maestro session (left-bar agent) owns this MCP
// subprocess. The fast path is env injection at agent-CLI spawn time, which
// works for any agent CLI that propagates parent env to its MCP subprocesses
// (Claude Code, OpenCode). For agent CLIs that do NOT propagate parent env
// (notably Codex), SESSION_ID will be absent and the bridge falls back to
// PID-based resolution: we always include process.ppid in the hello payload
// and the bridge walks the process tree to find the owning agent. Failing
// here would make coworking unusable in Codex; failing closed for unknown
// callers happens in the bridge instead.
const SESSION_ID = process.env.MAESTRO_COWORKING_SESSION_ID || null;

const SERVER_INFO = { name: 'maestro-coworking', version: '1.0.0' };
// Listed newest-first. The MCP spec says: if the client requests a version we
// support, echo it back; otherwise pick one we do support. We pick the newest
// supported version as the fallback (also our preferred version when the client
// sends nothing). https://modelcontextprotocol.io/specification/.../basic/lifecycle
const SUPPORTED_PROTOCOL_VERSIONS = [
  '2025-11-25',
  '2025-06-18',
  '2025-03-26',
  '2024-11-05',
  '2024-10-07',
];
const TOOLS = [
  {
    name: 'list_terminals',
    description:
      'List terminal tabs in your own Maestro session (the agent that spawned this MCP server). ' +
      'Returns an array of { id, cwd, title } where id is a stable readable handle like "term:3". ' +
      'You will never see terminals belonging to other Maestro sessions, regardless of which tab the user has focused.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
  },
  {
    name: 'read_terminal',
    description:
      'Read the scrollback contents of a terminal tab by id, scoped to your own Maestro session. ' +
      'Optionally tail-truncate to the last N lines.',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'Terminal id, e.g. "term:3" (from list_terminals).' },
        lines: { type: 'integer', minimum: 1, description: 'If set, return only the last N lines.' },
      },
      required: ['id'],
      additionalProperties: false,
    },
  },
  {
    name: 'list_browsers',
    description:
      'List the in-app browser tabs in your own Maestro session (the agent that spawned this MCP server). ' +
      'Returns an array of { id, url, title, canGoBack, canGoForward, isLoading } where id is a stable handle like "browser:2". ' +
      'You only ever see browser tabs in your own session, regardless of which tab the user has focused.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
  },
  {
    name: 'get_browser_url',
    description:
      'Get the current URL, title, and loading state of a browser tab by id, scoped to your own Maestro session. ' +
      'Returns { id, url, title, isLoading }; poll isLoading (or list_browsers) to confirm a page finished loading before reading it.',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'Browser tab id, e.g. "browser:2" (from list_browsers).' },
      },
      required: ['id'],
      additionalProperties: false,
    },
  },
  {
    name: 'read_browser',
    description:
      'Read the rendered text (or HTML) of a browser tab by id, scoped to your own Maestro session. ' +
      'Waits for the page to finish loading before reading, so a read right after browser_navigate returns the loaded page (bounded; a still-loading page is read best-effort). ' +
      'Use format "text" or "innerText" for the visible page text, or "html" for the page markup. ' +
      'Optionally scope the read to the first element matching a CSS selector, and/or cap the output with maxChars (head-truncated).',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'Browser tab id, e.g. "browser:2".' },
        format: {
          type: 'string',
          enum: ['text', 'innerText', 'html'],
          description: 'Output format (default "text").',
        },
        selector: {
          type: 'string',
          description: 'If set, read only the first element matching this CSS selector.',
        },
        maxChars: { type: 'integer', minimum: 1, description: 'If set, return only the first N characters.' },
      },
      required: ['id'],
      additionalProperties: false,
    },
  },
  {
    name: 'browser_navigate',
    description:
      'Navigate a browser tab to a URL (or search query), scoped to your own Maestro session. ' +
      'Requires browser interaction to be enabled for this agent.',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'Browser tab id, e.g. "browser:2".' },
        url: { type: 'string', description: 'URL or search text to load.' },
      },
      required: ['id', 'url'],
      additionalProperties: false,
    },
  },
  {
    name: 'browser_back',
    description:
      'Navigate a browser tab back in history (scoped to your own session; requires browser interaction enabled).',
    inputSchema: {
      type: 'object',
      properties: { id: { type: 'string', description: 'Browser tab id, e.g. "browser:2".' } },
      required: ['id'],
      additionalProperties: false,
    },
  },
  {
    name: 'browser_forward',
    description:
      'Navigate a browser tab forward in history (requires browser interaction enabled).',
    inputSchema: {
      type: 'object',
      properties: { id: { type: 'string', description: 'Browser tab id, e.g. "browser:2".' } },
      required: ['id'],
      additionalProperties: false,
    },
  },
  {
    name: 'browser_reload',
    description: 'Reload a browser tab (requires browser interaction enabled).',
    inputSchema: {
      type: 'object',
      properties: { id: { type: 'string', description: 'Browser tab id, e.g. "browser:2".' } },
      required: ['id'],
      additionalProperties: false,
    },
  },
  {
    name: 'browser_stop',
    description: 'Stop loading a browser tab (requires browser interaction enabled).',
    inputSchema: {
      type: 'object',
      properties: { id: { type: 'string', description: 'Browser tab id, e.g. "browser:2".' } },
      required: ['id'],
      additionalProperties: false,
    },
  },
  {
    name: 'browser_click',
    description:
      'Click the first element matching a CSS selector in a browser tab (requires browser interaction enabled).',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'Browser tab id, e.g. "browser:2".' },
        selector: { type: 'string', description: 'CSS selector of the element to click.' },
      },
      required: ['id', 'selector'],
      additionalProperties: false,
    },
  },
  {
    name: 'browser_type',
    description:
      'Type text into the first element matching a CSS selector (sets value, fires input/change events). Requires browser interaction enabled.',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'Browser tab id, e.g. "browser:2".' },
        selector: { type: 'string', description: 'CSS selector of the input/textarea.' },
        text: { type: 'string', description: 'Text to set as the value.' },
      },
      required: ['id', 'selector', 'text'],
      additionalProperties: false,
    },
  },
  {
    name: 'browser_eval',
    description:
      'Evaluate JavaScript in a browser tab and return the result. Powerful; requires browser interaction enabled.',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'Browser tab id, e.g. "browser:2".' },
        code: { type: 'string', description: 'JavaScript expression or statements to run in the page.' },
      },
      required: ['id', 'code'],
      additionalProperties: false,
    },
  },
  {
    name: 'browser_screenshot',
    description:
      'Capture a PNG screenshot of a browser tab (returned as an image). Most reliable on the visible tab. Requires browser interaction enabled.',
    inputSchema: {
      type: 'object',
      properties: { id: { type: 'string', description: 'Browser tab id, e.g. "browser:2".' } },
      required: ['id'],
      additionalProperties: false,
    },
  },
  {
    name: 'browser_wait_for',
    description:
      'Wait until an element matching a CSS selector appears in a browser tab (or the timeout elapses). ' +
      'Useful after navigate/click to let dynamic pages settle. Requires browser interaction enabled.',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'Browser tab id, e.g. "browser:2".' },
        selector: { type: 'string', description: 'CSS selector to wait for.' },
        timeoutMs: {
          type: 'integer',
          minimum: 1,
          maximum: 30000,
          description: 'Max wait in milliseconds (default 10000, capped at 30000).',
        },
      },
      required: ['id', 'selector'],
      additionalProperties: false,
    },
  },
  {
    name: 'browser_new_tab',
    description:
      'Open a new in-app browser tab in your own Maestro session, optionally at a URL. ' +
      'Set ephemeral=true for an incognito-style tab: its session is isolated and kept in memory only (no cookies/logins are ever written to disk). ' +
      'The new tab does not have an id yet: call list_browsers afterwards to address it. ' +
      'Requires browser interaction enabled.',
    inputSchema: {
      type: 'object',
      properties: {
        url: { type: 'string', description: 'URL to load (defaults to the browser home page).' },
        ephemeral: {
          type: 'boolean',
          description: 'If true, use an in-memory session (no persisted cookies/logins).',
        },
      },
      additionalProperties: false,
    },
  },
  {
    name: 'browser_close_tab',
    description:
      'Close a browser tab by id, scoped to your own Maestro session. Requires browser interaction enabled.',
    inputSchema: {
      type: 'object',
      properties: { id: { type: 'string', description: 'Browser tab id, e.g. "browser:2".' } },
      required: ['id'],
      additionalProperties: false,
    },
  },
];

// Browser interaction tools all funnel through the bridge 'browserInteract'
// method (gated by the per-agent permission in main). Each entry maps a tool
// name to the BrowserOp it sends.
const BROWSER_INTERACTION_OPS = {
  browser_navigate: (a) => ({ kind: 'navigate', url: a.url }),
  browser_back: () => ({ kind: 'back' }),
  browser_forward: () => ({ kind: 'forward' }),
  browser_reload: () => ({ kind: 'reload' }),
  browser_stop: () => ({ kind: 'stop' }),
  browser_click: (a) => ({ kind: 'click', selector: a.selector }),
  browser_type: (a) => ({ kind: 'type', selector: a.selector, text: a.text }),
  browser_eval: (a) => ({ kind: 'eval', code: a.code }),
  browser_screenshot: () => ({ kind: 'screenshot' }),
  browser_wait_for: (a) => ({ kind: 'waitFor', selector: a.selector, timeoutMs: a.timeoutMs }),
  browser_new_tab: (a) => ({ kind: 'newTab', url: a.url, ephemeral: a.ephemeral }),
  browser_close_tab: () => ({ kind: 'closeTab' }),
};

// ---------- Bridge client (lazy, single shared connection) ----------
let bridgeConn = null;
let bridgeBuffer = '';
let connectPromise = null;
let helloPromise = null;
const pending = new Map();
let nextRpcId = 1;
// Cap each in-flight RPC so a wedged-but-not-disconnected bridge can't stall
// tools/call indefinitely. 10s comfortably accommodates a renderer round-trip
// (the main-process side caps the buffer-fetch at 5s) plus jitter.
const BRIDGE_RPC_TIMEOUT_MS = 10000;
// Interaction ops (browserInteract) can block on a human approval dialog, so they
// get a much longer cap than reads. Kept slightly above the main-process browser-op
// timeout so the main side fails first with a clean message.
const BRIDGE_INTERACT_TIMEOUT_MS = 330000;

function rejectAllPending(err) {
  for (const p of pending.values()) p.reject(err);
  pending.clear();
}

function connectBridge() {
  if (bridgeConn) return Promise.resolve(bridgeConn);
  // Concurrent callers must share a single in-flight connection so the module-
  // level bridgeBuffer doesn't get spliced across multiple sockets.
  if (connectPromise) return connectPromise;

  connectPromise = new Promise((resolve, reject) => {
    const c = net.createConnection({ path: SOCKET_PATH }, () => {
      c.setEncoding('utf8');
      // Reset shared buffer for this fresh connection.
      bridgeBuffer = '';
      c.on('data', (chunk) => {
        bridgeBuffer += chunk;
        let nl;
        while ((nl = bridgeBuffer.indexOf('\n')) !== -1) {
          const line = bridgeBuffer.slice(0, nl).trim();
          bridgeBuffer = bridgeBuffer.slice(nl + 1);
          if (!line) continue;
          let msg;
          try {
            msg = JSON.parse(line);
          } catch {
            continue;
          }
          const p = pending.get(msg.id);
          if (!p) continue;
          pending.delete(msg.id);
          if (msg.error) p.reject(new Error(msg.error.message || 'bridge error'));
          else p.resolve(msg.result);
        }
      });
      c.on('error', (err) => {
        rejectAllPending(err);
        bridgeConn = null;
        helloPromise = null;
      });
      // Reject pending RPCs on a clean close too - otherwise their callers
      // would hang forever waiting for a reply that will never come.
      c.on('close', () => {
        rejectAllPending(new Error('coworking bridge: connection closed'));
        bridgeConn = null;
        helloPromise = null;
      });
      bridgeConn = c;
      resolve(c);
    });
    c.once('error', reject);
  }).finally(() => {
    connectPromise = null;
  });
  return connectPromise;
}

// Send a single RPC against an already-open bridge connection. No handshake
// gating here - the gate lives in bridgeCall() so this primitive can also be
// used to perform the handshake itself.
function rpc(conn, method, params, timeoutMs) {
  const id = nextRpcId++;
  let timeoutHandle = null;
  const promise = new Promise((resolve, reject) => {
    timeoutHandle = setTimeout(() => {
      // Drop the pending entry first so the response (if it ever arrives) is a no-op.
      pending.delete(id);
      reject(new Error('coworking bridge: rpc timed out'));
    }, timeoutMs || BRIDGE_RPC_TIMEOUT_MS);
    pending.set(id, {
      resolve: (value) => {
        if (timeoutHandle) clearTimeout(timeoutHandle);
        resolve(value);
      },
      reject: (err) => {
        if (timeoutHandle) clearTimeout(timeoutHandle);
        reject(err);
      },
    });
  });
  try {
    conn.write(JSON.stringify({ id, method, params }) + '\n');
  } catch (err) {
    if (timeoutHandle) clearTimeout(timeoutHandle);
    pending.delete(id);
    throw err;
  }
  return promise;
}

// Perform the session-binding handshake exactly once per connection. Cached on
// helloPromise so concurrent first callers share one in-flight handshake; the
// connect-close handlers reset it so a reconnect re-handshakes.
//
// We send sessionId when env propagation worked, and *always* send ppid so the
// bridge can fall back to walking the process tree when env propagation didn't.
// The bridge prefers sessionId if both are present.
function bridgeHello(conn) {
  if (helloPromise) return helloPromise;
  const params = {};
  if (SESSION_ID) params.sessionId = SESSION_ID;
  if (typeof process.ppid === 'number' && process.ppid > 0) params.ppid = process.ppid;
  helloPromise = rpc(conn, 'hello', params).catch((err) => {
    helloPromise = null;
    throw err;
  });
  return helloPromise;
}

async function bridgeCall(method, params, timeoutMs) {
  // Capture the resolved socket locally so that if bridgeConn is nulled out
  // between the await and the write (e.g. by a synchronous error handler), we
  // either succeed or surface the failure immediately instead of leaking the
  // pending entry.
  const conn = bridgeConn || (await connectBridge());
  if (!conn || conn.destroyed) {
    throw new Error('coworking bridge: not connected');
  }
  await bridgeHello(conn);
  return rpc(conn, method, params, timeoutMs);
}

// ---------- MCP stdio framing ----------
let stdinBuffer = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => {
  stdinBuffer += chunk;
  let nl;
  while ((nl = stdinBuffer.indexOf('\n')) !== -1) {
    const line = stdinBuffer.slice(0, nl).trim();
    stdinBuffer = stdinBuffer.slice(nl + 1);
    if (!line) continue;
    let msg;
    try {
      msg = JSON.parse(line);
    } catch {
      continue;
    }
    handleMessage(msg).catch((err) => {
      process.stderr.write('[maestro-coworking] handler error: ' + String(err) + '\n');
    });
  }
});

function send(msg) {
  process.stdout.write(JSON.stringify(msg) + '\n');
}

function rpcResult(id, result) {
  return { jsonrpc: '2.0', id, result };
}
function rpcError(id, code, message) {
  return { jsonrpc: '2.0', id, error: { code, message } };
}

async function handleMessage(msg) {
  // Notifications: no id, no response.
  if (msg.id === undefined || msg.id === null) {
    // 'notifications/initialized' and others - ignore.
    return;
  }
  const { id, method, params } = msg;
  try {
    if (method === 'initialize') {
      const requested = params && params.protocolVersion;
      const protocolVersion =
        typeof requested === 'string' && SUPPORTED_PROTOCOL_VERSIONS.indexOf(requested) !== -1
          ? requested
          : SUPPORTED_PROTOCOL_VERSIONS[0];
      send(
        rpcResult(id, {
          protocolVersion,
          serverInfo: SERVER_INFO,
          capabilities: { tools: {} },
        })
      );
      return;
    }
    if (method === 'ping') {
      send(rpcResult(id, {}));
      return;
    }
    if (method === 'tools/list') {
      send(rpcResult(id, { tools: TOOLS }));
      return;
    }
    if (method === 'tools/call') {
      const name = params && params.name;
      const args = (params && params.arguments) || {};
      if (name === 'list_terminals') {
        const result = await bridgeCall('listTerminals', {});
        const text = JSON.stringify(result, null, 2);
        send(rpcResult(id, { content: [{ type: 'text', text }] }));
        return;
      }
      if (name === 'read_terminal') {
        const result = await bridgeCall('readTerminal', args);
        const header =
          'terminal=' +
          (result && result.id) +
          ' totalLines=' +
          (result && result.totalLines) +
          (result && result.truncated ? ' (tail-truncated)' : '');
        const text = header + '\n----- BEGIN BUFFER -----\n' + (result && result.content) + '\n----- END BUFFER -----';
        send(rpcResult(id, { content: [{ type: 'text', text }] }));
        return;
      }
      if (name === 'list_browsers') {
        const result = await bridgeCall('listBrowsers', {});
        const text = JSON.stringify(result, null, 2);
        send(rpcResult(id, { content: [{ type: 'text', text }] }));
        return;
      }
      if (name === 'get_browser_url') {
        const result = await bridgeCall('getBrowserUrl', args);
        const text = JSON.stringify(result, null, 2);
        send(rpcResult(id, { content: [{ type: 'text', text }] }));
        return;
      }
      if (name === 'read_browser') {
        const result = await bridgeCall('readBrowser', args);
        const header =
          'browser=' + (result && result.id) +
          ' url=' + (result && result.url) +
          ' format=' + (result && result.format) +
          ' totalChars=' + (result && result.totalChars) +
          (result && result.truncated ? ' (head-truncated)' : '');
        const text =
          header + '\n----- BEGIN PAGE -----\n' + (result && result.content) + '\n----- END PAGE -----';
        send(rpcResult(id, { content: [{ type: 'text', text }] }));
        return;
      }
      if (Object.prototype.hasOwnProperty.call(BROWSER_INTERACTION_OPS, name)) {
        const op = BROWSER_INTERACTION_OPS[name](args);
        const result = await bridgeCall('browserInteract', { id: args.id, op: op }, BRIDGE_INTERACT_TIMEOUT_MS);
        if (op.kind === 'screenshot' && result && result.dataUrl) {
          const base64 = String(result.dataUrl).replace(/^data:image\/[^;]+;base64,/, '');
          send(rpcResult(id, { content: [{ type: 'image', data: base64, mimeType: 'image/png' }] }));
          return;
        }
        const text = JSON.stringify(result, null, 2);
        send(rpcResult(id, { content: [{ type: 'text', text: text }] }));
        return;
      }
      send(rpcError(id, -32601, 'Unknown tool: ' + String(name)));
      return;
    }
    send(rpcError(id, -32601, 'Unknown method: ' + String(method)));
  } catch (err) {
    send(rpcError(id, -32000, err && err.message ? err.message : String(err)));
  }
}

// Keep stdin alive so the agent's MCP client controls our lifecycle.
process.stdin.on('end', () => process.exit(0));
process.on('SIGINT', () => process.exit(0));
process.on('SIGTERM', () => process.exit(0));
`;

/** Returns the contents of the bundled MCP server script. */
export function getCoworkingServerScript(): string {
	return COWORKING_SCRIPT_SOURCE;
}
