/**
 * Unit tests for `removeSubscriptionFromYaml` — the rewriter that powers
 * `time.once` self-destruct after a fire.
 *
 * Uses a real temp directory so we exercise the actual on-disk write path
 * (atomic rename, leading-comment preservation). Filesystem failures are
 * simulated by `vi.spyOn(fs.promises, ...)` rather than full module mocks
 * so the rest of the module — path resolution, yaml dump — runs unmodified.
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import * as yaml from 'js-yaml';

vi.mock('../../../main/utils/sentry', () => ({
	captureException: vi.fn(),
}));

import { removeSubscriptionFromYaml } from '../../../main/cue/cue-self-destruct';

let projectRoot = '';
const HEADER = '# Pipeline: Tasks\n# Auto-generated by maestro-cli cue schedule\n\n';

beforeEach(() => {
	projectRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'cue-self-destruct-'));
	fs.mkdirSync(path.join(projectRoot, '.maestro'), { recursive: true });
});

afterEach(() => {
	vi.restoreAllMocks();
	if (projectRoot && fs.existsSync(projectRoot)) {
		fs.rmSync(projectRoot, { recursive: true, force: true });
	}
});

function writeYaml(body: object, header = ''): string {
	const dumped = yaml.dump(body, { lineWidth: -1, noRefs: true, sortKeys: false });
	const filePath = path.join(projectRoot, '.maestro', 'cue.yaml');
	fs.writeFileSync(filePath, header + dumped, 'utf-8');
	return filePath;
}

function readYaml(): { raw: string; parsed: Record<string, unknown> } {
	const filePath = path.join(projectRoot, '.maestro', 'cue.yaml');
	const raw = fs.readFileSync(filePath, 'utf-8');
	return { raw, parsed: yaml.load(raw) as Record<string, unknown> };
}

describe('removeSubscriptionFromYaml', () => {
	it('removes the named sub from a multi-sub file and preserves the others', async () => {
		writeYaml({
			subscriptions: [
				{
					name: 'task-2026-05-22-1400-aaaa1111-notify',
					event: 'time.once',
					action: 'notify',
					agent_id: 'a',
					fire_at: '2026-05-22T14:00:00Z',
					notify: { message: 'a' },
				},
				{
					name: 'heartbeat-1',
					event: 'time.heartbeat',
					interval_minutes: 5,
					prompt: 'check status',
				},
				{
					name: 'task-2026-05-22-1500-bbbb2222-notify',
					event: 'time.once',
					action: 'notify',
					agent_id: 'b',
					fire_at: '2026-05-22T15:00:00Z',
					notify: { message: 'b' },
				},
			],
		});

		const result = await removeSubscriptionFromYaml(
			projectRoot,
			'task-2026-05-22-1400-aaaa1111-notify'
		);

		expect(result.removed).toBe(true);
		const { parsed } = readYaml();
		const names = (parsed.subscriptions as Array<{ name: string }>).map((s) => s.name);
		expect(names).toEqual(['heartbeat-1', 'task-2026-05-22-1500-bbbb2222-notify']);
	});

	it('preserves the leading `# Pipeline:` comment header', async () => {
		writeYaml(
			{
				subscriptions: [
					{
						name: 'task-x',
						event: 'time.once',
						action: 'notify',
						agent_id: 'a',
						fire_at: '2026-05-22T14:00:00Z',
						notify: { message: 'r' },
					},
					{
						name: 'keep-me',
						event: 'time.heartbeat',
						interval_minutes: 10,
						prompt: 'tick',
					},
				],
			},
			HEADER
		);

		const result = await removeSubscriptionFromYaml(projectRoot, 'task-x');
		expect(result.removed).toBe(true);

		const { raw } = readYaml();
		expect(raw.startsWith(HEADER)).toBe(true);
		// Sanity-check that the sub was actually removed from the body
		// underneath the header (and the surviving sub remains).
		expect(raw).not.toContain('name: task-x');
		expect(raw).toContain('name: keep-me');
	});

	it('no-ops (returns removed: false) when the name does not exist', async () => {
		writeYaml({
			subscriptions: [
				{
					name: 'keep-me',
					event: 'time.heartbeat',
					interval_minutes: 5,
					prompt: 'tick',
				},
			],
		});

		const before = readYaml().raw;
		const result = await removeSubscriptionFromYaml(projectRoot, 'never-existed');
		expect(result.removed).toBe(false);
		expect(result.reason).toMatch(/not present/);

		// File is untouched.
		const after = readYaml().raw;
		expect(after).toBe(before);
	});

	it('returns removed: false when the cue.yaml file is missing', async () => {
		// No file written. `resolveCueConfigPath` returns null and the
		// rewriter bails before any IO.
		const result = await removeSubscriptionFromYaml(projectRoot, 'whatever');
		expect(result.removed).toBe(false);
		expect(result.reason).toMatch(/cue\.yaml not found/);
	});

	it('returns removed: false when fs.readFile throws', async () => {
		writeYaml({
			subscriptions: [
				{
					name: 'task-x',
					event: 'time.once',
					action: 'notify',
					agent_id: 'a',
					fire_at: '2026-05-22T14:00:00Z',
					notify: { message: 'r' },
				},
			],
		});

		const readSpy = vi
			.spyOn(fs.promises, 'readFile')
			.mockRejectedValueOnce(new Error('EIO: simulated read failure'));

		const result = await removeSubscriptionFromYaml(projectRoot, 'task-x');
		expect(result.removed).toBe(false);
		expect(result.reason).toMatch(/read failed:.*EIO: simulated read failure/);
		// Make sure we actually intercepted the call we meant to.
		expect(readSpy).toHaveBeenCalledTimes(1);
	});

	it('returns removed: false with a parse reason on malformed YAML', async () => {
		const filePath = path.join(projectRoot, '.maestro', 'cue.yaml');
		// Intentionally broken YAML — js-yaml will throw on load.
		fs.writeFileSync(filePath, 'subscriptions:\n  - name: oops\n    bad: [unclosed\n', 'utf-8');

		const result = await removeSubscriptionFromYaml(projectRoot, 'oops');
		expect(result.removed).toBe(false);
		expect(result.reason).toMatch(/yaml parse failed/);
	});

	it('returns removed: false when subscriptions key is missing entirely', async () => {
		writeYaml({ settings: { timeout_minutes: 10 } });
		const result = await removeSubscriptionFromYaml(projectRoot, 'anything');
		expect(result.removed).toBe(false);
		expect(result.reason).toMatch(/subscriptions array missing/);
	});

	it('preserves unrelated top-level keys (settings) after a successful remove', async () => {
		writeYaml({
			settings: { timeout_minutes: 30, max_concurrent: 4 },
			subscriptions: [
				{
					name: 'task-x',
					event: 'time.once',
					action: 'notify',
					agent_id: 'a',
					fire_at: '2026-05-22T14:00:00Z',
					notify: { message: 'r' },
				},
				{ name: 'survivor', event: 'time.heartbeat', interval_minutes: 5, prompt: 'tick' },
			],
		});

		const result = await removeSubscriptionFromYaml(projectRoot, 'task-x');
		expect(result.removed).toBe(true);

		const { parsed } = readYaml();
		expect(parsed.settings).toEqual({ timeout_minutes: 30, max_concurrent: 4 });
		const names = (parsed.subscriptions as Array<{ name: string }>).map((s) => s.name);
		expect(names).toEqual(['survivor']);
	});
});
